name: Test Release Process

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [main]
    paths: 
      - '.github/workflows/publish.yml'
      - 'pyproject.toml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
        echo "✓ Package built and checked successfully"
    
    - name: Test package installation
      run: |
        pip install dist/*.whl
        python -c "import pbi2snow; print(f'Package version: {pbi2snow.__version__}')"
        python -m pbi2snow.cli --help
        echo "✓ Package installs and runs correctly"
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-dist
        path: dist/
        retention-days: 1